# Generated by Django 4.2.1 on 2023-05-29 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='cargo.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Number must be a digit from 1000 to 9999 + a capital letter at the end (e.g., 2534B).', regex='^[1-9]\\d{3}[A-Z]$')]),
        ),
    ]
